### ISSUE TITLE
Enabling www.pauseai.info

### ISSUE THREAD

**Issue by joepio** [joepio/pauseai#19]
Probably a DNS thing

**Comment by joepio** [comment]
Changed it in openprovider DNS

**Comment by anthonybailey** [comment]
## Local Reproduction Results

I was able to reproduce 500 errors locally using `netlify serve` by causing edge function process termination.

### Test Setup
- Branch: main
- Config: `PARAGLIDE_LOCALES=en` (English-only)
- Server: `NODE_ENV=production netlify serve --port 8890`
- Edge function process: Deno runtime (confirmed via `ps aux`)

### Findings

**Method 1: Manual process termination**
- Killing edge function process via `kill <PID>` → subsequent requests to `/statement` return 500 (response time ~3ms)
- Static/prerendered routes continue to work normally

**Method 2: Code-triggered process termination**
- Created test endpoint `/api/test-edge-crash` with methods:
  - `process.exit(1)` → kills edge function process
  - `Deno.exit(1)` → kills edge function process  
  - Stack overflow → process survives, returns 500 but continues running

**Behavior after edge function death:**
- `/statement`: 500 (~3ms response time)
- `/api/*` endpoints: 500 (~3ms response time)
- `/` homepage: 200 (prerendered)
- `/learn`: 200 (prerendered)

The swift response times (~3ms) for 500 errors match the production behavior described.

**Code that successfully kills edge function process:**
```typescript
// Method works in Deno environment
if (typeof Deno \!== 'undefined' && Deno.exit) {
    Deno.exit(1)
}

// Method works if process object available
if (typeof process \!== 'undefined' && process.exit) {
    process.exit(1)
}
```

This suggests production 500s could be caused by edge function processes terminating unexpectedly, rather than request-level errors.
